# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/ryan/Documents/Prog Projects/ImageProcessing"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/ryan/Documents/Prog Projects/ImageProcessing"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ryan/Documents/Prog Projects/ImageProcessing/CMakeFiles" "/home/ryan/Documents/Prog Projects/ImageProcessing/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ryan/Documents/Prog Projects/ImageProcessing/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named detectionTest

# Build rule for target.
detectionTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 detectionTest
.PHONY : detectionTest

# fast build rule for target.
detectionTest/fast:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/build
.PHONY : detectionTest/fast

#=============================================================================
# Target rules for targets named objectTracker

# Build rule for target.
objectTracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objectTracker
.PHONY : objectTracker

# fast build rule for target.
objectTracker/fast:
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/build
.PHONY : objectTracker/fast

src/actionEndEffector/ActionEndEffector.o: src/actionEndEffector/ActionEndEffector.cpp.o

.PHONY : src/actionEndEffector/ActionEndEffector.o

# target to build an object file
src/actionEndEffector/ActionEndEffector.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/actionEndEffector/ActionEndEffector.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/actionEndEffector/ActionEndEffector.cpp.o
.PHONY : src/actionEndEffector/ActionEndEffector.cpp.o

src/actionEndEffector/ActionEndEffector.i: src/actionEndEffector/ActionEndEffector.cpp.i

.PHONY : src/actionEndEffector/ActionEndEffector.i

# target to preprocess a source file
src/actionEndEffector/ActionEndEffector.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/actionEndEffector/ActionEndEffector.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/actionEndEffector/ActionEndEffector.cpp.i
.PHONY : src/actionEndEffector/ActionEndEffector.cpp.i

src/actionEndEffector/ActionEndEffector.s: src/actionEndEffector/ActionEndEffector.cpp.s

.PHONY : src/actionEndEffector/ActionEndEffector.s

# target to generate assembly for a file
src/actionEndEffector/ActionEndEffector.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/actionEndEffector/ActionEndEffector.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/actionEndEffector/ActionEndEffector.cpp.s
.PHONY : src/actionEndEffector/ActionEndEffector.cpp.s

src/actionEndEffector/ArduinoFire.o: src/actionEndEffector/ArduinoFire.cpp.o

.PHONY : src/actionEndEffector/ArduinoFire.o

# target to build an object file
src/actionEndEffector/ArduinoFire.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/actionEndEffector/ArduinoFire.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/actionEndEffector/ArduinoFire.cpp.o
.PHONY : src/actionEndEffector/ArduinoFire.cpp.o

src/actionEndEffector/ArduinoFire.i: src/actionEndEffector/ArduinoFire.cpp.i

.PHONY : src/actionEndEffector/ArduinoFire.i

# target to preprocess a source file
src/actionEndEffector/ArduinoFire.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/actionEndEffector/ArduinoFire.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/actionEndEffector/ArduinoFire.cpp.i
.PHONY : src/actionEndEffector/ArduinoFire.cpp.i

src/actionEndEffector/ArduinoFire.s: src/actionEndEffector/ArduinoFire.cpp.s

.PHONY : src/actionEndEffector/ArduinoFire.s

# target to generate assembly for a file
src/actionEndEffector/ArduinoFire.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/actionEndEffector/ArduinoFire.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/actionEndEffector/ArduinoFire.cpp.s
.PHONY : src/actionEndEffector/ArduinoFire.cpp.s

src/camera/Camera.o: src/camera/Camera.cpp.o

.PHONY : src/camera/Camera.o

# target to build an object file
src/camera/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/Camera.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/Camera.cpp.o
.PHONY : src/camera/Camera.cpp.o

src/camera/Camera.i: src/camera/Camera.cpp.i

.PHONY : src/camera/Camera.i

# target to preprocess a source file
src/camera/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/Camera.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/Camera.cpp.i
.PHONY : src/camera/Camera.cpp.i

src/camera/Camera.s: src/camera/Camera.cpp.s

.PHONY : src/camera/Camera.s

# target to generate assembly for a file
src/camera/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/Camera.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/Camera.cpp.s
.PHONY : src/camera/Camera.cpp.s

src/camera/IpCamera.o: src/camera/IpCamera.cpp.o

.PHONY : src/camera/IpCamera.o

# target to build an object file
src/camera/IpCamera.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/IpCamera.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/IpCamera.cpp.o
.PHONY : src/camera/IpCamera.cpp.o

src/camera/IpCamera.i: src/camera/IpCamera.cpp.i

.PHONY : src/camera/IpCamera.i

# target to preprocess a source file
src/camera/IpCamera.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/IpCamera.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/IpCamera.cpp.i
.PHONY : src/camera/IpCamera.cpp.i

src/camera/IpCamera.s: src/camera/IpCamera.cpp.s

.PHONY : src/camera/IpCamera.s

# target to generate assembly for a file
src/camera/IpCamera.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/IpCamera.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/IpCamera.cpp.s
.PHONY : src/camera/IpCamera.cpp.s

src/camera/SingleImage.o: src/camera/SingleImage.cpp.o

.PHONY : src/camera/SingleImage.o

# target to build an object file
src/camera/SingleImage.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/SingleImage.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/SingleImage.cpp.o
.PHONY : src/camera/SingleImage.cpp.o

src/camera/SingleImage.i: src/camera/SingleImage.cpp.i

.PHONY : src/camera/SingleImage.i

# target to preprocess a source file
src/camera/SingleImage.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/SingleImage.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/SingleImage.cpp.i
.PHONY : src/camera/SingleImage.cpp.i

src/camera/SingleImage.s: src/camera/SingleImage.cpp.s

.PHONY : src/camera/SingleImage.s

# target to generate assembly for a file
src/camera/SingleImage.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/SingleImage.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/SingleImage.cpp.s
.PHONY : src/camera/SingleImage.cpp.s

src/camera/VideoFromFile.o: src/camera/VideoFromFile.cpp.o

.PHONY : src/camera/VideoFromFile.o

# target to build an object file
src/camera/VideoFromFile.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/VideoFromFile.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/VideoFromFile.cpp.o
.PHONY : src/camera/VideoFromFile.cpp.o

src/camera/VideoFromFile.i: src/camera/VideoFromFile.cpp.i

.PHONY : src/camera/VideoFromFile.i

# target to preprocess a source file
src/camera/VideoFromFile.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/VideoFromFile.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/VideoFromFile.cpp.i
.PHONY : src/camera/VideoFromFile.cpp.i

src/camera/VideoFromFile.s: src/camera/VideoFromFile.cpp.s

.PHONY : src/camera/VideoFromFile.s

# target to generate assembly for a file
src/camera/VideoFromFile.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/camera/VideoFromFile.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/camera/VideoFromFile.cpp.s
.PHONY : src/camera/VideoFromFile.cpp.s

src/detection/BackgroundSubtractionDetector.o: src/detection/BackgroundSubtractionDetector.cpp.o

.PHONY : src/detection/BackgroundSubtractionDetector.o

# target to build an object file
src/detection/BackgroundSubtractionDetector.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/detection/BackgroundSubtractionDetector.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/detection/BackgroundSubtractionDetector.cpp.o
.PHONY : src/detection/BackgroundSubtractionDetector.cpp.o

src/detection/BackgroundSubtractionDetector.i: src/detection/BackgroundSubtractionDetector.cpp.i

.PHONY : src/detection/BackgroundSubtractionDetector.i

# target to preprocess a source file
src/detection/BackgroundSubtractionDetector.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/detection/BackgroundSubtractionDetector.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/detection/BackgroundSubtractionDetector.cpp.i
.PHONY : src/detection/BackgroundSubtractionDetector.cpp.i

src/detection/BackgroundSubtractionDetector.s: src/detection/BackgroundSubtractionDetector.cpp.s

.PHONY : src/detection/BackgroundSubtractionDetector.s

# target to generate assembly for a file
src/detection/BackgroundSubtractionDetector.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/detection/BackgroundSubtractionDetector.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/detection/BackgroundSubtractionDetector.cpp.s
.PHONY : src/detection/BackgroundSubtractionDetector.cpp.s

src/detection/Detector.o: src/detection/Detector.cpp.o

.PHONY : src/detection/Detector.o

# target to build an object file
src/detection/Detector.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/detection/Detector.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/detection/Detector.cpp.o
.PHONY : src/detection/Detector.cpp.o

src/detection/Detector.i: src/detection/Detector.cpp.i

.PHONY : src/detection/Detector.i

# target to preprocess a source file
src/detection/Detector.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/detection/Detector.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/detection/Detector.cpp.i
.PHONY : src/detection/Detector.cpp.i

src/detection/Detector.s: src/detection/Detector.cpp.s

.PHONY : src/detection/Detector.s

# target to generate assembly for a file
src/detection/Detector.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/detection/Detector.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/detection/Detector.cpp.s
.PHONY : src/detection/Detector.cpp.s

src/detection/ThresholdDetector.o: src/detection/ThresholdDetector.cpp.o

.PHONY : src/detection/ThresholdDetector.o

# target to build an object file
src/detection/ThresholdDetector.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/detection/ThresholdDetector.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/detection/ThresholdDetector.cpp.o
.PHONY : src/detection/ThresholdDetector.cpp.o

src/detection/ThresholdDetector.i: src/detection/ThresholdDetector.cpp.i

.PHONY : src/detection/ThresholdDetector.i

# target to preprocess a source file
src/detection/ThresholdDetector.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/detection/ThresholdDetector.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/detection/ThresholdDetector.cpp.i
.PHONY : src/detection/ThresholdDetector.cpp.i

src/detection/ThresholdDetector.s: src/detection/ThresholdDetector.cpp.s

.PHONY : src/detection/ThresholdDetector.s

# target to generate assembly for a file
src/detection/ThresholdDetector.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/detection/ThresholdDetector.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/detection/ThresholdDetector.cpp.s
.PHONY : src/detection/ThresholdDetector.cpp.s

src/main/detectionTest.o: src/main/detectionTest.cpp.o

.PHONY : src/main/detectionTest.o

# target to build an object file
src/main/detectionTest.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/main/detectionTest.cpp.o
.PHONY : src/main/detectionTest.cpp.o

src/main/detectionTest.i: src/main/detectionTest.cpp.i

.PHONY : src/main/detectionTest.i

# target to preprocess a source file
src/main/detectionTest.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/main/detectionTest.cpp.i
.PHONY : src/main/detectionTest.cpp.i

src/main/detectionTest.s: src/main/detectionTest.cpp.s

.PHONY : src/main/detectionTest.s

# target to generate assembly for a file
src/main/detectionTest.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/main/detectionTest.cpp.s
.PHONY : src/main/detectionTest.cpp.s

src/main/trackerRunner.o: src/main/trackerRunner.cpp.o

.PHONY : src/main/trackerRunner.o

# target to build an object file
src/main/trackerRunner.cpp.o:
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/main/trackerRunner.cpp.o
.PHONY : src/main/trackerRunner.cpp.o

src/main/trackerRunner.i: src/main/trackerRunner.cpp.i

.PHONY : src/main/trackerRunner.i

# target to preprocess a source file
src/main/trackerRunner.cpp.i:
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/main/trackerRunner.cpp.i
.PHONY : src/main/trackerRunner.cpp.i

src/main/trackerRunner.s: src/main/trackerRunner.cpp.s

.PHONY : src/main/trackerRunner.s

# target to generate assembly for a file
src/main/trackerRunner.cpp.s:
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/main/trackerRunner.cpp.s
.PHONY : src/main/trackerRunner.cpp.s

src/motor/AngleCalculator.o: src/motor/AngleCalculator.cpp.o

.PHONY : src/motor/AngleCalculator.o

# target to build an object file
src/motor/AngleCalculator.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/motor/AngleCalculator.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/motor/AngleCalculator.cpp.o
.PHONY : src/motor/AngleCalculator.cpp.o

src/motor/AngleCalculator.i: src/motor/AngleCalculator.cpp.i

.PHONY : src/motor/AngleCalculator.i

# target to preprocess a source file
src/motor/AngleCalculator.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/motor/AngleCalculator.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/motor/AngleCalculator.cpp.i
.PHONY : src/motor/AngleCalculator.cpp.i

src/motor/AngleCalculator.s: src/motor/AngleCalculator.cpp.s

.PHONY : src/motor/AngleCalculator.s

# target to generate assembly for a file
src/motor/AngleCalculator.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/motor/AngleCalculator.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/motor/AngleCalculator.cpp.s
.PHONY : src/motor/AngleCalculator.cpp.s

src/motor/Motor.o: src/motor/Motor.cpp.o

.PHONY : src/motor/Motor.o

# target to build an object file
src/motor/Motor.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/motor/Motor.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/motor/Motor.cpp.o
.PHONY : src/motor/Motor.cpp.o

src/motor/Motor.i: src/motor/Motor.cpp.i

.PHONY : src/motor/Motor.i

# target to preprocess a source file
src/motor/Motor.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/motor/Motor.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/motor/Motor.cpp.i
.PHONY : src/motor/Motor.cpp.i

src/motor/Motor.s: src/motor/Motor.cpp.s

.PHONY : src/motor/Motor.s

# target to generate assembly for a file
src/motor/Motor.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/motor/Motor.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/motor/Motor.cpp.s
.PHONY : src/motor/Motor.cpp.s

src/motor/ServoMotor.o: src/motor/ServoMotor.cpp.o

.PHONY : src/motor/ServoMotor.o

# target to build an object file
src/motor/ServoMotor.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/motor/ServoMotor.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/motor/ServoMotor.cpp.o
.PHONY : src/motor/ServoMotor.cpp.o

src/motor/ServoMotor.i: src/motor/ServoMotor.cpp.i

.PHONY : src/motor/ServoMotor.i

# target to preprocess a source file
src/motor/ServoMotor.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/motor/ServoMotor.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/motor/ServoMotor.cpp.i
.PHONY : src/motor/ServoMotor.cpp.i

src/motor/ServoMotor.s: src/motor/ServoMotor.cpp.s

.PHONY : src/motor/ServoMotor.s

# target to generate assembly for a file
src/motor/ServoMotor.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/motor/ServoMotor.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/motor/ServoMotor.cpp.s
.PHONY : src/motor/ServoMotor.cpp.s

src/stereoCamera/StereoCamera.o: src/stereoCamera/StereoCamera.cpp.o

.PHONY : src/stereoCamera/StereoCamera.o

# target to build an object file
src/stereoCamera/StereoCamera.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/stereoCamera/StereoCamera.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/stereoCamera/StereoCamera.cpp.o
.PHONY : src/stereoCamera/StereoCamera.cpp.o

src/stereoCamera/StereoCamera.i: src/stereoCamera/StereoCamera.cpp.i

.PHONY : src/stereoCamera/StereoCamera.i

# target to preprocess a source file
src/stereoCamera/StereoCamera.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/stereoCamera/StereoCamera.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/stereoCamera/StereoCamera.cpp.i
.PHONY : src/stereoCamera/StereoCamera.cpp.i

src/stereoCamera/StereoCamera.s: src/stereoCamera/StereoCamera.cpp.s

.PHONY : src/stereoCamera/StereoCamera.s

# target to generate assembly for a file
src/stereoCamera/StereoCamera.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/stereoCamera/StereoCamera.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/stereoCamera/StereoCamera.cpp.s
.PHONY : src/stereoCamera/StereoCamera.cpp.s

src/stereoCamera/StereoCameraWithBackground.o: src/stereoCamera/StereoCameraWithBackground.cpp.o

.PHONY : src/stereoCamera/StereoCameraWithBackground.o

# target to build an object file
src/stereoCamera/StereoCameraWithBackground.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/stereoCamera/StereoCameraWithBackground.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/stereoCamera/StereoCameraWithBackground.cpp.o
.PHONY : src/stereoCamera/StereoCameraWithBackground.cpp.o

src/stereoCamera/StereoCameraWithBackground.i: src/stereoCamera/StereoCameraWithBackground.cpp.i

.PHONY : src/stereoCamera/StereoCameraWithBackground.i

# target to preprocess a source file
src/stereoCamera/StereoCameraWithBackground.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/stereoCamera/StereoCameraWithBackground.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/stereoCamera/StereoCameraWithBackground.cpp.i
.PHONY : src/stereoCamera/StereoCameraWithBackground.cpp.i

src/stereoCamera/StereoCameraWithBackground.s: src/stereoCamera/StereoCameraWithBackground.cpp.s

.PHONY : src/stereoCamera/StereoCameraWithBackground.s

# target to generate assembly for a file
src/stereoCamera/StereoCameraWithBackground.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/stereoCamera/StereoCameraWithBackground.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/stereoCamera/StereoCameraWithBackground.cpp.s
.PHONY : src/stereoCamera/StereoCameraWithBackground.cpp.s

src/tracking/KalmanTracker.o: src/tracking/KalmanTracker.cpp.o

.PHONY : src/tracking/KalmanTracker.o

# target to build an object file
src/tracking/KalmanTracker.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/tracking/KalmanTracker.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/tracking/KalmanTracker.cpp.o
.PHONY : src/tracking/KalmanTracker.cpp.o

src/tracking/KalmanTracker.i: src/tracking/KalmanTracker.cpp.i

.PHONY : src/tracking/KalmanTracker.i

# target to preprocess a source file
src/tracking/KalmanTracker.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/tracking/KalmanTracker.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/tracking/KalmanTracker.cpp.i
.PHONY : src/tracking/KalmanTracker.cpp.i

src/tracking/KalmanTracker.s: src/tracking/KalmanTracker.cpp.s

.PHONY : src/tracking/KalmanTracker.s

# target to generate assembly for a file
src/tracking/KalmanTracker.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/tracking/KalmanTracker.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/tracking/KalmanTracker.cpp.s
.PHONY : src/tracking/KalmanTracker.cpp.s

src/tracking/Tracker.o: src/tracking/Tracker.cpp.o

.PHONY : src/tracking/Tracker.o

# target to build an object file
src/tracking/Tracker.cpp.o:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/tracking/Tracker.cpp.o
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/tracking/Tracker.cpp.o
.PHONY : src/tracking/Tracker.cpp.o

src/tracking/Tracker.i: src/tracking/Tracker.cpp.i

.PHONY : src/tracking/Tracker.i

# target to preprocess a source file
src/tracking/Tracker.cpp.i:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/tracking/Tracker.cpp.i
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/tracking/Tracker.cpp.i
.PHONY : src/tracking/Tracker.cpp.i

src/tracking/Tracker.s: src/tracking/Tracker.cpp.s

.PHONY : src/tracking/Tracker.s

# target to generate assembly for a file
src/tracking/Tracker.cpp.s:
	$(MAKE) -f CMakeFiles/detectionTest.dir/build.make CMakeFiles/detectionTest.dir/src/tracking/Tracker.cpp.s
	$(MAKE) -f CMakeFiles/objectTracker.dir/build.make CMakeFiles/objectTracker.dir/src/tracking/Tracker.cpp.s
.PHONY : src/tracking/Tracker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... detectionTest"
	@echo "... objectTracker"
	@echo "... src/actionEndEffector/ActionEndEffector.o"
	@echo "... src/actionEndEffector/ActionEndEffector.i"
	@echo "... src/actionEndEffector/ActionEndEffector.s"
	@echo "... src/actionEndEffector/ArduinoFire.o"
	@echo "... src/actionEndEffector/ArduinoFire.i"
	@echo "... src/actionEndEffector/ArduinoFire.s"
	@echo "... src/camera/Camera.o"
	@echo "... src/camera/Camera.i"
	@echo "... src/camera/Camera.s"
	@echo "... src/camera/IpCamera.o"
	@echo "... src/camera/IpCamera.i"
	@echo "... src/camera/IpCamera.s"
	@echo "... src/camera/SingleImage.o"
	@echo "... src/camera/SingleImage.i"
	@echo "... src/camera/SingleImage.s"
	@echo "... src/camera/VideoFromFile.o"
	@echo "... src/camera/VideoFromFile.i"
	@echo "... src/camera/VideoFromFile.s"
	@echo "... src/detection/BackgroundSubtractionDetector.o"
	@echo "... src/detection/BackgroundSubtractionDetector.i"
	@echo "... src/detection/BackgroundSubtractionDetector.s"
	@echo "... src/detection/Detector.o"
	@echo "... src/detection/Detector.i"
	@echo "... src/detection/Detector.s"
	@echo "... src/detection/ThresholdDetector.o"
	@echo "... src/detection/ThresholdDetector.i"
	@echo "... src/detection/ThresholdDetector.s"
	@echo "... src/main/detectionTest.o"
	@echo "... src/main/detectionTest.i"
	@echo "... src/main/detectionTest.s"
	@echo "... src/main/trackerRunner.o"
	@echo "... src/main/trackerRunner.i"
	@echo "... src/main/trackerRunner.s"
	@echo "... src/motor/AngleCalculator.o"
	@echo "... src/motor/AngleCalculator.i"
	@echo "... src/motor/AngleCalculator.s"
	@echo "... src/motor/Motor.o"
	@echo "... src/motor/Motor.i"
	@echo "... src/motor/Motor.s"
	@echo "... src/motor/ServoMotor.o"
	@echo "... src/motor/ServoMotor.i"
	@echo "... src/motor/ServoMotor.s"
	@echo "... src/stereoCamera/StereoCamera.o"
	@echo "... src/stereoCamera/StereoCamera.i"
	@echo "... src/stereoCamera/StereoCamera.s"
	@echo "... src/stereoCamera/StereoCameraWithBackground.o"
	@echo "... src/stereoCamera/StereoCameraWithBackground.i"
	@echo "... src/stereoCamera/StereoCameraWithBackground.s"
	@echo "... src/tracking/KalmanTracker.o"
	@echo "... src/tracking/KalmanTracker.i"
	@echo "... src/tracking/KalmanTracker.s"
	@echo "... src/tracking/Tracker.o"
	@echo "... src/tracking/Tracker.i"
	@echo "... src/tracking/Tracker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

